### ISSUE TITLE
最後一碼檢查碼為0時誤判為失敗

### ISSUE THREAD

**Issue by SnowZero** [lmanliang/taiwan_check#1]
感謝您提供的套件
依照身分證規範
https://web.fg.tp.edu.tw/~anny/idtest.htm?fbclid=IwAR0pI0ymRmanb3sx2noxsfYO1UgzSBVyh3VIM-U3Sl_TaGg6ZrezNT5srwg
4. 若餘數為 0 時，則設定其檢查碼為 0 
此規則未判斷到

例：T110106230

**Comment by lmanliang** [comment]
感謝
已更新github
